name: Perre
favicon: null
layout_spectrum: 0.8033066219650209
typography_spectrum: 0.80734
title: Perre DiCarlo on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26353c'
    - '#f97048'
    - '#fafafa'
    - '#d4cdbf'
    - '#818a8e'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
