name: Perre
favicon: null
layout_spectrum: 0
typography_spectrum: 0.80734
title: Perre DiCarlo on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#85d053'
    - '#ededed'
    - '#f8e760'
    - '#a5a3aa'
    - '#544e5d'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
