typography_spectrum: 0.921
content_rating:
  adult: false
color:
  brandColors:
    - '#eef5e5'
    - '#a87f5d'
    - '#422130'
    - '#d4caae'
    - '#6c4f3b'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.51028
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Perre DiCarlo
  url: perredicarlo.com
name: Perre
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Perre DiCarlo on The Grid
purpose: []
