name: Perre
favicon: null
layout_spectrum: 0.51028
typography_spectrum: 0.921
title: Perre DiCarlo on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eef5e5'
    - '#a87f5d'
    - '#422130'
    - '#d4caae'
    - '#6c4f3b'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
