name: Perre
favicon: null
layout_spectrum: 0.8033066219650209
typography_spectrum: 0.80734
title: Perre DiCarlo on The Grid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d8d6ca'
    - '#9ba54e'
    - '#2c312b'
    - '#e09f69'
    - '#5f645e'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
